- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes

- name: extract artifact
  become: yes
  unarchive:
    src: ~/project/backend_artifact.tar.gz
    dest: .
- name: start app
  become: yes
  shell: |
    npm run build
    pm2 stop all
    pm2 start npm -- start
